# Generated by Django 4.0 on 2025-02-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='lon',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Короткое описание'),
        ),
    ]
