# Generated by Django 4.2 on 2025-02-27 16:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number_image']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='place',
            name='long_descriptio',
        ),
        migrations.AddField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Длинное описание'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(db_index=True, upload_to='images/', verbose_name='КАРТИНКА'),
        ),
        migrations.AlterField(
            model_name='image',
            name='number_image',
            field=models.IntegerField(default=0, verbose_name='ПОЗИЦИЯ'),
        ),
    ]
