# Generated by Django 4.2 on 2025-03-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(db_index=True, upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Позиция'),
        ),
    ]
