# Generated by Django 4.2 on 2025-03-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='number_image',
        ),
        migrations.AddField(
            model_name='image',
            name='number',
            field=models.IntegerField(db_index=True, default=0, verbose_name='ПОЗИЦИЯ'),
        ),
    ]
